### PR TITLE
Add roll control and reaction wheel

### PR DESCRIPTION
**Pull request by SammyOina**
for integration with flight control to allow use of raw values as well as from dmp

### CODE REVIEW

**Comment by Mike-Kimani** [comment]
Lgtm. Pending tuning of the PID values which you could do later.

**Review by kimanimichael — COMMENTED** [review]
Generally lgtm. However, I've seen flight control uses a different MPU6050 library compared to the rest of avionics. Aren't you going to be using the same values from the avionics Kalman filter?

Also @0x6f736f646f @georgebangeboss We should merge the Launch branch to main for easier integration with other teams.

**Comment by SammyOina** [comment]
> Generally lgtm. However, I've seen flight control uses a different MPU6050 library compared to the rest of avionics. Aren't you going to be using the same values from the avionics Kalman filter?
> 
> Also @0x6f736f646f @georgebangeboss We should merge the Launch branch to main for easier integration with other teams.

FC is not using kalman values at the moment but instead obtaining dmp values hence the library change. Having variability in data processing ie kalman and dmp can allow us to compare values after flight

**Comment by rodneyosodo** [comment]
Closing this as it is a duplicate and an older version of #26

**Pull request closed without merging**
